# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

production:
  adapter: postgresql
  encoding: unicode
  database: beta1_development
  pool: 5
  host: localhost
  port: 5432
development:
  adapter: postgresql
  encoding: unicode
  database: beta1_development
  pool: 5
  host: localhost
  username: postgres
  password: seedbank
  port: 5432

